application/skeletodo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
]

skeletodo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('tasks/', include('tasks.urls')),
]

tasks/urls.py
from django.urls import path

from . import views


app_name = 'tasks'
urlpatterns = [
    path('', views.ListView.as_view(), name='list'),
    path('create/', views.CreateView.as_view(), name='create'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/delete/', views.DeleteView.as_view(), name='delete'),
]

application/todoitems/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from skeletodo.models import BaseModel


class Todoitem(BaseModel):
    """A user's todo item."""

    user = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
        related_name='todoitems',
        verbose_name=_('User'),
    )

    text = models.CharField(  # TextField doesn't give a fuck about max_length
        blank=False,  # Django suggests avoiding blank=True for CharField
        max_length=4096,
        verbose_name=_('Text'),
    )

    def save(self, *args, **kwargs):  # noqa: D102
        self.full_clean()
        super().save(*args, **kwargs)

skeletodo/models.py
from django.db import models


class BaseModel(models.Model):
    """
    Inherit all models from this model.

    Store methods and stuff common for all models.
    """

    class Meta:
        abstract = True

    def update(self, **attributes):
        """
        Update self attributes and save.

        Use in tests to reduce code amount.
        """
        for name in attributes:
            setattr(self, name, attributes[name])
        else:
            self.save()

tasks/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _

from skeletodo.models import BaseModel


class Task(BaseModel):
    """A user's todo item."""

    user = models.ForeignKey(
        'auth.User',
        on_delete=models.CASCADE,
        related_name='tasks',
        verbose_name=_('User'),
    )

    text = models.CharField(  # TextField doesn't give a fuck about max_length
        blank=False,  # Django suggests avoiding blank=True for CharField
        max_length=4096,
        verbose_name=_('Text'),
    )

    def save(self, *args, **kwargs):  # noqa: D102
        self.full_clean()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('tasks:detail', args=[self.id])

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic

from .models import Task


@method_decorator(login_required, name='dispatch')
class ListView(generic.ListView):  # noqa: D101
    template_name = 'tasks/list.html'
    context_object_name = 'tasks'
    queryset = Task.objects.all()


@method_decorator(login_required, name='dispatch')
class CreateView(generic.CreateView):  # noqa: D101
    model = Task
    fields = ['text']
    template_name = 'tasks/create.html'

    def form_valid(self, form):
        """Set user from request and call super."""
        user = self.request.user
        form.instance.user = user
        return super().form_valid(form)


@method_decorator(login_required, name='dispatch')
class DetailView(generic.DetailView):  # noqa: D101
    model = Task
    template_name = 'tasks/detail.html'


@method_decorator(login_required, name='dispatch')
class DeleteView(generic.DeleteView):  # noqa: D101
    model = Task
    template_name = 'tasks/delete.html'
    success_url = reverse_lazy('tasks:list')

tasks/templates/tasks/create.html
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Save">
</form>

tasks/templates/tasks/delete.html
<form method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete "{{ object }}"?</p>
  <input type="submit" value="Confirm">
</form>

tasks/templates/tasks/detail.html
<p>{{ task.text }}</p>

<a href="{% url 'tasks:list' %}">View all</a>
<br>
<a href="{% url 'tasks:delete' task.id %}">Delete</a>

tasks/templates/tasks/index.html
{% if tasks %}
    <ul>
    {% for task in tasks %}
        <li><a href="{% url 'tasks:detail' task.id %}">{{ task.text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No tasks are available.</p>
{% endif %}

<a href="{% url 'tasks:create' %}">Create</a>

tasks/templates/tasks/list.html
{% if tasks %}
    <ul>
    {% for task in tasks %}
        <li><a href="{% url 'tasks:detail' task.id %}">{{ task.text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No tasks are available.</p>
{% endif %}

<a href="{% url 'tasks:create' %}">Create</a>